### ISSUE TITLE
Local organizers

### ISSUE THREAD

**Issue by miguelnunezwb** [ComplexNetTSP/netmob2024#11]
I added the new figure files Do they work?

**Comment by vgauthier** [comment]
@miguelnunezwb I still need the Trevor's photo and also a link for each one of you toward your profile page ?

**Comment by miguelnunezwb** [comment]
@vgauthier could You please add  Trevor Monroe (https://www.linkedin.com/in/trevormonroe/) and Wenlan Zhang (https://www.zhangwenlan.com/)

**Comment by vgauthier** [comment]
@miguelnunezwb I have done all the worldbank people 
I still need to do mine 
Should I add more people ?

**Comment by miguelnunezwb** [comment]
Yes please add yourself. We should add one more person from WB Lakesh but she didn't send her photo. I'm not sure if she wants to be in there.

**Comment by miguelnunezwb** [comment]
Please add Lakech Tsegaye (https://www.linkedin.com/in/lakech-tsegaye-5b769548/)

**Comment by vgauthier** [comment]
> Please add Lakech Tsegaye (https://www.linkedin.com/in/lakech-tsegaye-5b769548/)

done in #[1c40acb](https://github.com/ComplexNetTSP/netmob2024/commit/1c40acb9619071b53ffcccb290eb27a214833152)

**Comment by miguelnunezwb** [comment]
Hello Vincent,

Could you please add these 3 people as organizers?

Daniel Smolyak Naman Awasthi (https://www.cs.umd.edu/people/nawasthi) and Saad Abrar (https://www.cs.umd.edu/people/sabrar). Their pictures are uploaded.

Thanks a lot
