### ISSUE TITLE
Finalize the challenge text

### ISSUE THREAD

**Issue by vgauthier** [ComplexNetTSP/netmob2024#12]
We need to update the text about the challenge

**Comment by vgauthier** [comment]
@miguelnunezwb  what do you think if I change your text as follows:

The goal of the NetMob 2024 Data Challenge is to foster competition focused on extracting and applying insights from mobility data. The goal of this year's challenge is multi-fold:
* Increase understanding of how to derive population density from mobility data samples, 
* Assess the impact of climate conditions or climate-related hazards on human mobility patterns
* Identify various applications of mobility-based metrics to inform public policy. 

Maybe you should just mention also the countries where the data will be collected from ?

**Comment by miguelnunezwb** [comment]
I'm not 100% sure about the tracks. We need to confirm we Spectus. That's why I tried to be very generic. By the way There is a website only for the data challenge: https://netmob2023challenge.networks.imdea.org/ We can add somenthing loke that for details. What do you thing?

**Comment by miguelnunezwb** [comment]
I don't know what happened to the challenge text. Could we please update with the wollowing text:

The NetMob 2024 Data Challenge seeks to foster competition centered on extracting and utilizing insights from mobility data. Beyond academic progress, the goal of this year’s challenge is to cultivate a global environment where enthusiasm for analyzing mobility data can thrive alongside practical development objectives. Specifically, it targets countries in the Global South, aligning with the Sustainable Development Goals (SDGs). Participants are encouraged to focus on one of the following three topics in their proposals. 

Admitted participants shall submit two-page extended abstracts in PDF format including title, author(s), affiliation(s) and email address(es) on the first page, describing their preliminary results from the dataset analysis by July 8.
Selected participants will be invited to submit by 16 September a final report consisting of: a complete document without page limits that will be kept confidential, and used to select the challenge awardees as well as to take a final decision on whether the work will be presented at the conference as a talk or a poster; and, 2-page summary of the work that will appear in the public NetMob 2024 Book of Abstracts.

**Comment by vgauthier** [comment]
> I'm not 100% sure about the tracks. We need to confirm we Spectus. That's why I tried to be very generic. By the way There is a website only for the data challenge: https://netmob2023challenge.networks.imdea.org/ We can add somenthing loke that for details. What do you thing?

@miguelnunezwb I am not sure to understand what you said

**Comment by miguelnunezwb** [comment]
My apologies @vgauthier In fact, Spectus didn't confirm yet if they are OK with the three topics: 

*Increase understanding of how to derive population density from mobility data samples.
*Assess the impact of climate conditions or climate-related hazards on human mobility patterns.
*Identify various applications of mobility-based metrics to inform public policy.

They should be but want to make it clear since the data granularity could impact the feasibility of the topics. Thus, maybe for now we can just take out the 3 topics from the website.

Additionally, i saw that for last edition they have another webpage detailing the Data Challenge topics, datasets, etc. So i was asking your opinion about it. Do you think we should have anotehr website only for the challenge details or do we integrate the details  in the main website?

**Comment by vgauthier** [comment]
> Additionally, i saw that for last edition they have another webpage detailing the Data Challenge topics, datasets, etc. So i was asking your opinion about it. Do you think we should have anotehr website only for the challenge details or do we integrate the details in the main website?

@miguelnunezwb Ha, yes we can do that, but it depend if you don't need dynamic webpage (no form etc) I can create a new page dedicated to the challenge to current website. if you need dynamic page we have to create a dedicated webpage hosted outside in the netmob site.

**Comment by vgauthier** [comment]
@miguelnunezwb could you check the challenge terms and condition and tell me if its ok ?

**Comment by vgauthier** [comment]
@miguelnunezwb  I also add a link for the submission, could your tell me if its ok as well
