### ISSUE TITLE
Trevor minor sugestions

### ISSUE THREAD

**Issue by miguelnunezwb** [ComplexNetTSP/netmob2024#15]
Minor suggestions:

MC à Main Campus
Add: Farragut North (Red Line)
Remove: imo red underline style is awk

**Comment by miguelnunezwb** [comment]
I changed MC and add Farragut North (Red Line). No sure if it is easy to change de red underline.

**Comment by vgauthier** [comment]
I just commited some change, take a look on vercel, is it what you aks for ?

**Comment by miguelnunezwb** [comment]
Thanks Vincent !! Those were the suggestion. 

Sveta ask me if it is possible to hide the Program Committee section since we don't have the official names for reviewers. Additionally, she ask for changing "Local Organizers" to "Organizers"

**Comment by vgauthier** [comment]
I don't think it's a good idea to hide the program committee; the program committee is usually renewed from event to event. The program committee is there to help organize the program (find keynotes, speakers, etc.), not to review the papers.

**Comment by miguelnunezwb** [comment]
Done

**Comment by miguelnunezwb** [comment]
Close
