### ISSUE TITLE
open data challenge

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#16]
1. Update data challenge application link on the website
Could you please add the below text on the **Data Challenge** section: 
_Please apply to participate in the data challenge by completing the **Data Request Form** available here[link: https://datacatalog.worldbank.org/search/dataset/0066094/aggregated_mobility_and_density_data_for_the_netmob_2024_data_challenge]. All participants are required to review and agree to the Terms and Conditions before applying._

2. Update **conference and data challenge submission requirements**: please delete the requirement of 'Submissions should include the title, author(s), affiliation(s) and email address(es) on the first page.' from both **Main Event** and **Data Challenge**.

3. 2 more **PC members** to be added to the website, info in the google doc from email.

**Comment by vgauthier** [comment]
Hi @wenlanzhang 

Could you quickly check the [dev server](https://netmob2024.vercel.app/) to see if I have addressed all your requests?
