### ISSUE TITLE
PC Member Update

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#18]
Please update the new PC member: Riccardo Di Clemente
Info can be find in the google doc [https://docs.google.com/spreadsheets/d/1wAqBI8Ae_SgDf_w_bCDpMYk_YzgOmsnY/edit?usp=sharing&ouid=115823611615366949628&rtpof=true&sd=true](url)

**Comment by vgauthier** [comment]
Done in [5619a6d](https://github.com/ComplexNetTSP/netmob2024/commit/5619a6dc34ebd4a00b0e967d12e52ee596392318)
