### ISSUE TITLE
Data Challenge update

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#19]
Hi Vincent, 
could you please add this paragraph below on the data challenge section, it describes the award of the challenge: 

_Challenge winners and winning teams will be selected based on their final report submissions. As an award, the winners and winning teams will be granted six-months of access to the Spectus Data Cleanroom, which contains more granular privacy-preserving data. Spectus reserves the right to determine the specific conditions and scope of this access, ensuring alignment with their privacy policies._

maybe before 'Please apply to participate in the data challenge by completing the [Data Request Form](https://datacatalog.worldbank.org/search/dataset/0066094/aggregated_mobility_and_density_data_for_the_netmob_2024_data_challenge). All participants are required to review and agree to the Terms and Conditions before applying.' this sentence. Or wherever you think makes more sense. 

Many thanks.

**Comment by vgauthier** [comment]
Hi @wenlanzhang , 
Please look on the main website if its okay ?
Best 
V.

**Comment by wenlanzhang** [comment]
It looks great to me! Many thanks, Vincent!
