### ISSUE TITLE
deadline postpone

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#20]
Hi Vincent, 

Could you please change the 7th July in the first paragraph in the 'Challenge format' to 15th? to be consistent with the 'Important Dates'

Many thanks

**Comment by vgauthier** [comment]
Could you please check both the challenge dates and the mains events dates on the [dev website]( https://netmob2024.vercel.app/) before updating the main site 

thanks

**Comment by wenlanzhang** [comment]
> Could you please check both the challenge dates and the mains events dates on the [dev website](https://netmob2024.vercel.app/) before updating the main site
> 
> thanks

Hi, I think both looks good to me. Thank you!

**Comment by wenlanzhang** [comment]
Hi, I think there's no further change on this, please feel free to close.
