### ISSUE TITLE
Website Update

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#22]
Hi Vincent & Miguel, Could you please make the following changes on the website: 

Add a **Registration** section: 
- subsection: Registration fees
Add a table like this: 
![image](https://github.com/user-attachments/assets/d73c8ae0-1264-40c5-9bac-588ef171317d)
We have the same rate for industry and academic, and our rate would be: 
Student (student ID required): 
Early bird (until 30th of August) : 125 USD
Regular: 175 USD
Academic and Industry: 
Early bird (until 30th of August) : 250 USD
Regular: 350 USD

- subsection: Refund/Cancellation Policy
All registration refund requests must be sent via email to netmob2024@worldbank.org and received no later than September 27, 2024. A full refund, minus 25.00 USD for online registration, will be issued. For those who pay by credit card, refunds can only be processed to the credit card to which the original charge was made. Processing of the refunds may take over 30 days. Refund requests received after September 27, 2024 will not be honored. No-shows are subject to the full fee.

In the **Main Event** section: 
strike through the 
'_Submission website opening June 1, 2024
Submission deadline: July 15, 2024
Notification of acceptance: July 30, 2024_ ' 
since we have finished them. 

In the **Data Challenge** section: 
1. strike through the 
'[Abstract submission website opening](https://netmob24.hotcrp.com/): June 1, 2024
Challenge launch: June 10, 2024
Research proposal submission deadline: July 15, 2024
Notification of acceptance: July 30, 2024'
2. Remove the link to the '_Data Request Form_', cause we have closed it, and change that to '_Data Request Form (closed)_'

Add a **Travel Arrangement** section, 
- subsection: Visa Support Letters
'_As part of the visa application process, you may be required to include a visa support letter. To request a visa support letter, register for the conference and then fill out this form (https://forms.gle/fDtihV2PQhU82CrQ6). 
Visa support letters are answered in the order they are received. You will receive a PDF letter by email within 4-5 business days. Please note that we do not fax or mail visa support letters. Please print out your PDF letter and take it with you.
Please note that Support Letter will only be sent to participants who have registered and paid for the Conference. Should participants withdraw from the conference after the issue of Support Letter, the consulate will be notified of the withdrawal accordingly._'

- subsection: Nearby Hotels
_State plaza hotel: 2117 E St NW, Washington, DC 20037
Yours Truly DC Hotel - Vignette Collection by IHG: 1143 New Hampshire Ave NW, Washington, DC 20037
2500 Penn: 2500 Pennsylvania Avenue NW, Washington, DC 20037
Melrose Georgetown Hotel: 2430 Pennsylvania Avenue NW, Washington, DC 20037
Hampton Inn Washington, D.C./White House: 1729 H St NW, Washington, DC 20006
We encourage you to secure your accommodation as soon as possible, as rooms are expected to fill up quickly._

In the **Organizer** section
change Marta Gonzalez 's affiliation to '_University of California, Berkeley_'

**Comment by vgauthier** [comment]
@wenlanzhang @miguelnunezwb could you both check the [dev website](https://netmob2024.vercel.app/) before I update the main website 

Best

**Comment by wenlanzhang** [comment]
> @wenlanzhang @miguelnunezwb could you both check the [dev website](https://netmob2024.vercel.app/) before I update the main website
> 
> Best

Hi Vincent, Looks great to me! Many thanks to your work :)

**Comment by miguelnunezwb** [comment]
Looks ok for me

**Comment by vgauthier** [comment]
Hi @wenlanzhang @miguelnunezwb 
the main site has been updated
