### ISSUE TITLE
20240911 Update on programme and related matter

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#23]
Hi Vincent, 

As the conference approaching, we have a series of update to be made on the website, could you please have a look at the following: 

1. Add a **Schedule and Program** section 
- To present the schedule, can we use the last year's format: https://netmob.org/www23/#program_at_glance. Please find the session and schedule in the attached spreadsheet. 
- Can we add a link to the sessions which direct to a different page called **Program Overview** that summarised all papers and authors for each session. The authors can also be found in the spreadsheet. 
it could look like this: (we don't need the affliation)
![image](https://github.com/user-attachments/assets/9fa59bcb-fc31-4060-b8a5-db2394cab90c)

[Vnetmob2024_papers_sessions.xlsx](https://github.com/user-attachments/files/16971370/Vnetmob2024_papers_sessions.xlsx)
(ps: Here's quite a lot of information here, if anything seems weird, please feel free to let me double check)

- Can we add a **Keynote Speaker** section and add information about our keynote speader and their talks: 

Name: Neave O’Clery
Affliation: Centre for Advanced Spatial Analysis, University College London
Title: Can we do policy impact evaluation using mobile phone data in low data settings? 
Summary: Drawing on experience from two studies focused on Colombia, this talk will discuss the potential and challenges of policy impact evaluation using mobile phone data in low data settings. The first centres on the impact of covid lockdown policies (which varied by city in Colombia) on mobility patterns, and the second on the impact of opening of a new cable car in a poor peripheral area of Bogota.
![image](https://github.com/user-attachments/assets/0a476ab9-d48a-46c7-8bc5-a0ce73489b19)

Name: Ali Mostafavi
Affliation: Zachry Department of Civil Engineering, Texas A&M University
Title: Decoding the Anatomy of Resilient Communities Based on Human Mobility Shifts
Summary: This talk presents the synthesis of a series of studies in which various aspects of community resilience dynamics are characterized based on fluctuations in human mobility patterns. From a human-centric characterization of flood exposure to the evaluation of disrupted access to critical facilities and mapping of post-disaster lifestyle recovery, this talk showcases key applications of human mobility data for unraveling and monitoring the pulse of communities in the face of crises.
![image](https://github.com/user-attachments/assets/865fb949-bc93-4214-a0e6-2073494b4596)

3. Registration fees
strike through the Early Bird columns since the deadline has passed. 

4. In the **Data Challenge** section:
- strike through 'Challenge launch: June 10, 2024'
- add one more line of 'Final abstract submission deadline: September 16, 2024'
- change the 'Final report submission deadline: September 16, 2024' to 'Full report submission deadline: October 2, 2024' so that we can give participants more time to prepare.

**Comment by wenlanzhang** [comment]
It's quite a lot information to update here. Huge thanks to your work and time!!!

**Comment by vgauthier** [comment]
I think you check the preview of the NetMob website with the program included at the following address : [https://netmob2024.vercel.app/](https://netmob2024.vercel.app/)
let me know if you spot something missing

**Comment by wenlanzhang** [comment]
> I think you check the preview of the NetMob website with the program included at the following address : https://netmob2024.vercel.app/ let me know if you spot something missing

Hi Vincent,
I think the website looks amazing! Just two small things:

(1). Could you please add the sentence "The full conference program, including the schedule of talks and presentations, is available here [link to the program]"? This is in case people don’t notice the bar.
(2). Would it be possible to left-align the times in each timetable of the program? If it takes too long, feel free to ignore this—it’s a tiny detail.

I believe the website is ready to go after that. Thank you so much for all your effort! I’m sorry to have you working over the weekend and really appreciate it. I hope you get to enjoy the rest of it!

**Comment by vgauthier** [comment]
The program is online

**Comment by wenlanzhang** [comment]
Huge thank you to your work Vincent!!!

**Comment by wenlanzhang** [comment]
Hi Vincent, 
On the Monday schedule, paper _Urban Segregation and Daily Human Mobility Patterns in Berlin_ from session B has added one author, could you please add **Alejandra Rincon** as their third author? 
Sorry for the extra work, and thank you for your time. 
<img width="785" alt="image" src="https://github.com/user-attachments/assets/bed9a712-81e0-4777-8bdc-70779cc5e212">

**Comment by vgauthier** [comment]
it is done

**Comment by wenlanzhang** [comment]
Thank you so much!
