### ISSUE TITLE
20240918 Update on program

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#24]
Hi Vincent, 

Could you please help to update the following information: 

**Conference** section:
could you please add a 'Conference Program' before the 'The full conference program, including the schedule of talks and presentations, is available [here](https://netmob.org/program).' line, since we want it to be more obvious that people can see it. 

**Program** Page, **Monday Schedule**
Can we change the 'lunch' to 'Lunch and Conference Poster Session'

**Instructions**
We'll also want to add in the conference paper presentation and poster instructions like they had last year. The poster instructions are below, so we can already include those:

For authors of abstracts to be presented as posters
Format of posters is A0 in portrait orientation (84.1 cm width x 118.9 cm height, or 33.1 inches x 46.8 inches).
You need to print the poster on your own.
As you can see from the program, each conference poster is exhibited for one full day on October 7 (the first day of the conference) and each challenge poster is exhibited October 8 (the second day of the conference). You are welcome to set up your poster at any time between 8:30 (when the venue opens) and the end of the first coffee break (at 10:45). The official time allocated for attendees to browse posters is from 12:45 to 14:00 on Oct 7 and 12:15-13:30 on Oct 8, and we encourage you to stand by your poster during that time, after grabbing your lunch. You should remove your poster by the end of the day.

We are still working on the presentation instructions with Vanessa to see how we are collecting the presentations, so I will update later. I'm not really sure where's the best place to put this. Maybe in the program page and below the program title? 
 

Thank you so much for you time and work!

**Comment by vgauthier** [comment]
I have updated the web site sections in accordance with what you have mentioned in this issue. The updates should be online now!
Best

**Comment by wenlanzhang** [comment]
Thank you so much Vincent. 

Could you please also add this section in the **Program** page, we were working on this yesterday and sorry for the delay:

For authors of abstracts accepted for presentation as a talk
1. Each talk will be allocated 12 minutes plus 3 minutes for Q&A. We will have to enforce a strict compliance with timing due to a fairly packed program, so please make sure that you stay in the allotted 12 minutes with your presentation.
2. Prepare a PDF file with your slides and we will share a link for you to upload your presentation.
3. Note that NetMob 2024 will be a fully in-person event, and we do not have options for remote presentation.

**Comment by wenlanzhang** [comment]
I've seen the update! Thank you so much Vincent🙏!
