### ISSUE TITLE
20241002

### ISSUE THREAD

**Issue by wenlanzhang** [ComplexNetTSP/netmob2024#25]
**PC Member Update:**

Please remove the following from the PC list:
Anastasios Noulas
Nicholas K.W. Jones
Stefania Rubrichi

**Program Page Correction:**

The word "October" is misspelled for Monday and Tuesday.

There are some changes for the program, that hopefully I can update you tomorrow. 
Apologies in advance for the frequent updates lately—Thank you so much for your help and your patience!

**Comment by vgauthier** [comment]
hi it is done,

if you want to update the program you can do it directly in github by updating the following file
https://github.com/ComplexNetTSP/netmob2024/blob/main/src/components/data/program-days.tsx

best

**Comment by wenlanzhang** [comment]
Brilliant! Can you please invite me to be a collaborator so that I make easy change directly without bothering you too much?

**Comment by vgauthier** [comment]
I just sent you an invitation

**Comment by wenlanzhang** [comment]
Hi Vincent, I have updated the program in the demo web (https://netmob2024.vercel.app/program), can you please update the content to the main web please! Many thanks:).

**Comment by wenlanzhang** [comment]
I also added the papers for day3, can you please also make that visible please? 
<img width="978" alt="image" src="https://github.com/user-attachments/assets/e01d12a9-2350-418b-ad06-1180a2833be5">

**Comment by vgauthier** [comment]
great!, I pushed your update to the official webpage
