### ISSUE TITLE
Add Registration section

### ISSUE THREAD

**Issue by vgauthier** [ComplexNetTSP/netmob2024#4]
We should add a registration section in the main page

**Comment by vgauthier** [comment]
Added a new section but still need to add the final link

**Comment by miguelnunezwb** [comment]
Is it possible to hide the reghistration section and button in the top menu?

**Comment by vgauthier** [comment]
yes I can do that if you want

**Comment by vgauthier** [comment]
@miguelnunezwb  no new about the registration link ?
